### ISSUE TITLE
All targets

### ISSUE THREAD

**Issue by lublak** [Aurel300/ammer#52]
This list is only for documenting which interfaces exist.
(what can help is to autogenerate swig files? http://www.swig.org/)

| Target     | Interface                                                                                  | Implemented | Planned |
|------------|--------------------------------------------------------------------------------------------|-------------|---------|
| Javascript | [Emscript](https://emscripten.org/)                                                        | false       | false   |
| NodeJs     | [N-API](https://nodejs.org/api/n-api.html)                                                 | false       | **true**    |
| HashLink   | [hdll](https://github.com/HaxeFoundation/hashlink/wiki/HashLink-native-extension-tutorial) | **true**        | false   |
| Eval       | [cmxs/cmo](https://api.haxe.org/v/development/eval/vm/Context.html#loadPlugin)             | false       | **true**    |
| JVM        | [JNI](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/jniTOC.html)         | false       | false   |
| PHP7       | [Extension](https://stackoverflow.com/questions/3632160/how-to-make-a-php-extension)       | false       | false   |
| C++        | [CFFI or extern](http://hughsando.com/2016/02/10/cffi-prime-for-cffi-users/)               | **true**        | false   |
| Lua        | [C API](https://www.lua.org/pil/26.html)                                                   | **true**        | false   |
| C#         | [P/Invoke](https://docs.microsoft.com/en-us/dotnet/standard/native-interop/pinvoke)        | false       | false   |
| Python     | [ctypes](https://docs.python.org/3/extending/extending.html)                               | false       | false   |
| Java       | [JNI](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/jniTOC.html)         | false       | false   |
| Flash      | NO!                                                                                        | false       | false   |
| Neko       | [ndll](https://nekovm.org/doc/ffi/)                                                        | false       | false   |

**Comment by Aurel300** [comment]
Thanks for the links! I'm working on a restructuring of `ammer`. Here is the platform support I am aiming for:

| Platform   | Prototype? | Mechanism                                                                                                       | Note |
| ---------- | ---------- | --------------------------------------------------------------------------------------------------------------- | ---- |
| C++        | yes        | static link                                                                                                     |      |
| C++        |            | dynamic link                                                                                                    | not useful? |
| C#         | yes        | [P/Invoke](https://docs.microsoft.com/en-us/dotnet/standard/native-interop/pinvoke)                             |      |
| Eval       |            | [compiler plugins](https://api.haxe.org/v/development/eval/vm/Context.html#loadPlugin)                          | issues with dune builds |
| Flash      |            | [AIR native extensions](https://help.adobe.com/en_US/air/build/WS597e5dadb9cc1e0253f7d2fc1311b491071-8000.html) | (why bother?) |
| Hashlink   | yes        | [hdll](https://github.com/HaxeFoundation/hashlink/wiki/HashLink-native-extension-tutorial)                      |      |
| Hashlink/C |            | static link                                                                                                     | how to inline code into HL/C output? |
| Hashlink/C | yes        | dynamic link                                                                                                    |      |
| Javascript |            | [Deno FFI](https://doc.deno.land/deno/unstable/~/Deno.ForeignFunction)                                          |      |
| Javascript |            | [Emscripten](https://emscripten.org/)                                                                           |      |
| Javascript | yes        | [N-API](https://nodejs.org/api/n-api.html)                                                                      |      |
| Java       | yes        | [JNI](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/jniTOC.html)                              |      |
| JVM        | yes        | [JNI](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/jniTOC.html)                              |      |
| Lua        | yes        | [C API](https://www.lua.org/pil/26.html)                                                                        |      |
| Neko       | yes        | [ndll](https://nekovm.org/doc/ffi/)                                                                             |      |
| PHP7       |            | [extensions](https://stackoverflow.com/questions/3632160/how-to-make-a-php-extension)                           | not useful? not enabled on shared PHP servers... |
| Python     | yes        | [C API](https://docs.python.org/3/extending/extending.html)                                                     |      |

"Prototype" means I have a build that for now just sends ints back and forth. "Dynamic link" vs "static link" refers to whether the glue code itself is part of the compiled binary. For C++ the code is generated directly so it does not make much sense to generate code that dynamically links to glue code (that will then dynamically link to a native library). Likewise for HL/C although I'm not yet sure how I can accomplish this.

Regarding SWIG: I guess `ammer` could be a "target language" for SWIG. That is, it could hopefully generate the `ammer` library definitions that would then allow Haxe to connect to the library, without anybody having to figure out the Haxe-library mapping manually.

**Comment by Aurel300** [comment]
The underlying framework `ammer-core` is now [public](https://github.com/Aurel300/ammer-core). I will soon be replacing this repo with a complete rewrite based on `ammer-core`.
